// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StartupApp.Persistence;
using System;

namespace StartupApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20180217195116_initialTest")]
    partial class initialTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StartupApp.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Difficulty_Level");

                    b.Property<int?>("QuestionTypeId");

                    b.Property<string>("QuestionTypeType");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Difficulty");
                });

            modelBuilder.Entity("StartupApp.Models.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Questiontypes");
                });

            modelBuilder.Entity("StartupApp.Models.Difficulty", b =>
                {
                    b.HasOne("StartupApp.Models.QuestionType", "QuestionType")
                        .WithMany("Difficulty_Levels")
                        .HasForeignKey("QuestionTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
